### ISSUE TITLE
No longer installs

### ISSUE THREAD

**Issue by ioquatix** [shvets/selenium#2]
```
% selenium install
  downloading http://selenium.googlecode.com/files/selenium-server-2.37.0.zip... /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 404 Not Found (OpenURI::HTTPError)
    from /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
    from /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
    from /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
    from /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
    from /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
    from /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:717:in `open'
    from /home/samuel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:35:in `open'
    from /home/samuel/.rvm/gems/ruby-2.3.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:125:in `block in download_file_to'
    from /home/samuel/.rvm/gems/ruby-2.3.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:124:in `open'
    from /home/samuel/.rvm/gems/ruby-2.3.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:124:in `download_file_to'
    from /home/samuel/.rvm/gems/ruby-2.3.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:17:in `install'
    from /home/samuel/.rvm/gems/ruby-2.3.0/gems/selenium-0.2.11/lib/selenium/starter.rb:33:in `run'
    from /home/samuel/.rvm/gems/ruby-2.3.0/gems/selenium-0.2.11/bin/selenium:7:in `<top (required)>'
    from /home/samuel/.rvm/gems/ruby-2.3.0/bin/selenium:23:in `load'
    from /home/samuel/.rvm/gems/ruby-2.3.0/bin/selenium:23:in `<main>'
    from /home/samuel/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /home/samuel/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by enkanba** [comment]
I've got the same issue. @ioquatix , did you manage to install it?

**Comment by enkanba** [comment]
#3
